### ISSUE TITLE
Rails version

### ISSUE THREAD

**Issue by Surakarus** [gaelfokou/cama_autocomplete#1]
Camaleon CMS runs on rails 4.2.6, but your plugin requires rails 5.0.4. So how do I install your plugin without breaking dependencies? Thank you in advance.

**Comment by gaelfokou** [comment]
Thanks for the notice,
I've resolved the issue try to install again.

**Comment by Surakarus** [comment]
Works well, thanks! Although, I have to had added gem 'jquery-ui-rails'.

**Comment by gaelfokou** [comment]
Ok thanks,
Please don't forget to put a star on this repository if you like it...
