### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by Surakarus** [gaelfokou/cama_autocomplete#2]
For some reason, after reproducing all steps, mentioned in README, I can see text field, but it doesn't react to any text. What could cause such behavior? Thank you in advance.

**Comment by gaelfokou** [comment]
Remove the lignes bellow in your javascript file
//= require jquery //= require jquery_ujs

**Comment by Surakarus** [comment]
Already done, nothing changed

**Comment by gaelfokou** [comment]
Sorry go to the stape 6, I've forgoten this javascript code

<script type="text/javascript">
     $(document).ready(function() {
       new app.Posts;
     });
</script>

Add it in your layout and try again

**Comment by Surakarus** [comment]
It worked, thanks!

**Comment by gaelfokou** [comment]
You are welcome...
